### Amazon Web Services (AWS) configuration
###########################################

# key - AWS Access Key ID
key: AKIAJHU4H4D4ZQUB7URQ
# secret - AWS secret access key
secret: isVViyNBGvRJuM0N2pc7+ePiyrlkGraeGtvQi7nb
# region - Region name (e.g. 'us-east-1', 'us-west-1', 'us-west-2', 'eu-west-1', etc...)
region: us-east-1
# bucket title
bucket: laval-ugram-team-06


### Repository configuration ##############
###########################################

# relative or absolute path to your repository
path: ./dist

